os:
  - linux

language: python

python:

  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then sudo apt-get install python-tk; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then sudo apt-get install python-tk; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then sudo apt-get install python3-tk; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then sudo apt-get install python3-tk; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then sudo apt-get install python3-tk; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then sudo apt-get install python3-tk; fi
  #- sudo apt-get install tk-table

# command to run tests
script:
  - ./travis.sh